
package br.com.senac.uc15_etapa_4.telas;

import br.com.senac.uc15_etapa_4.persistencia.Usuario;


public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    private Usuario usuario;

    public TelaMenu(Usuario u) {
        initComponents();
        this.usuario = u;
    }
    
    
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonStatus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonBanco = new javax.swing.JButton();
        jButtonCondicao = new javax.swing.JButton();
        jButtonFornecedor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonCategoria = new javax.swing.JButton();
        jButtonComprador = new javax.swing.JButton();
        jButtonFamilia = new javax.swing.JButton();
        jButtonProduto = new javax.swing.JButton();
        jButtonUtilizacao = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(545, 382));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(188, 202, 211));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setName("Teste"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(188, 202, 211));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Geral", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel3.setToolTipText("");

        jButtonStatus.setBackground(new java.awt.Color(139, 173, 196));
        jButtonStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonStatus.setForeground(new java.awt.Color(51, 51, 51));
        jButtonStatus.setText("Status Cadastro");
        jButtonStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(188, 202, 211));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jButtonBanco.setBackground(new java.awt.Color(139, 173, 196));
        jButtonBanco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBanco.setForeground(new java.awt.Color(51, 51, 51));
        jButtonBanco.setText("Banco");
        jButtonBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBancoActionPerformed(evt);
            }
        });

        jButtonCondicao.setBackground(new java.awt.Color(139, 173, 196));
        jButtonCondicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCondicao.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCondicao.setText("Condição Pagamento");
        jButtonCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCondicaoActionPerformed(evt);
            }
        });

        jButtonFornecedor.setBackground(new java.awt.Color(139, 173, 196));
        jButtonFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFornecedor.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFornecedor.setText("Fornecedor");
        jButtonFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCondicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jButtonFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBanco)
                .addGap(18, 18, 18)
                .addComponent(jButtonCondicao)
                .addGap(18, 18, 18)
                .addComponent(jButtonFornecedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(188, 202, 211));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jButtonCategoria.setBackground(new java.awt.Color(139, 173, 196));
        jButtonCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCategoria.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCategoria.setText("Categoria");
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jButtonComprador.setBackground(new java.awt.Color(139, 173, 196));
        jButtonComprador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonComprador.setForeground(new java.awt.Color(51, 51, 51));
        jButtonComprador.setText("Comprador");
        jButtonComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompradorActionPerformed(evt);
            }
        });

        jButtonFamilia.setBackground(new java.awt.Color(139, 173, 196));
        jButtonFamilia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFamilia.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFamilia.setText("Família");
        jButtonFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFamiliaActionPerformed(evt);
            }
        });

        jButtonProduto.setBackground(new java.awt.Color(139, 173, 196));
        jButtonProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonProduto.setForeground(new java.awt.Color(51, 51, 51));
        jButtonProduto.setText("Produto");
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });

        jButtonUtilizacao.setBackground(new java.awt.Color(139, 173, 196));
        jButtonUtilizacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonUtilizacao.setForeground(new java.awt.Color(51, 51, 51));
        jButtonUtilizacao.setText("Utilização");
        jButtonUtilizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUtilizacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonComprador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jButtonFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUtilizacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jButtonProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCategoria)
                .addGap(18, 18, 18)
                .addComponent(jButtonComprador)
                .addGap(18, 18, 18)
                .addComponent(jButtonFamilia)
                .addGap(18, 18, 18)
                .addComponent(jButtonUtilizacao)
                .addGap(18, 18, 18)
                .addComponent(jButtonProduto)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusActionPerformed
        TelaStatus TelaStatus = new TelaStatus(usuario);
        TelaStatus.setVisible(true);
    }//GEN-LAST:event_jButtonStatusActionPerformed

    private void jButtonCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCondicaoActionPerformed
        // TODO add your handling code here:
        TelaCondicao TelaCondicao = new TelaCondicao(usuario);
        TelaCondicao.setVisible(true);
    }//GEN-LAST:event_jButtonCondicaoActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCategoria TelaCategoria = new TelaCategoria(usuario);
        TelaCategoria.setVisible(true);
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButtonCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompradorActionPerformed
        // TODO add your handling code here:
        TelaComprador TelaComprador = new TelaComprador(usuario);
        TelaComprador.setVisible(true);
    }//GEN-LAST:event_jButtonCompradorActionPerformed

    private void jButtonUtilizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUtilizacaoActionPerformed
        // TODO add your handling code here:
        TelaUtilizacao TelaUtilizacao = new TelaUtilizacao(usuario);
        TelaUtilizacao.setVisible(true);
    }//GEN-LAST:event_jButtonUtilizacaoActionPerformed

    private void jButtonBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBancoActionPerformed
        // TODO add your handling code here:
        TelaBanco TelaBanco = new TelaBanco(usuario);
        TelaBanco.setVisible(true);
    }//GEN-LAST:event_jButtonBancoActionPerformed

    private void jButtonFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedorActionPerformed
        // TODO add your handling code here:
        TelaFornecedor TelaFornecedor = new TelaFornecedor(usuario);
        TelaFornecedor.setVisible(true);
    }//GEN-LAST:event_jButtonFornecedorActionPerformed

    private void jButtonFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFamiliaActionPerformed
        // TODO add your handling code here:
        TelaFamilia TelaFamilia = new TelaFamilia(usuario);
        TelaFamilia.setVisible(true);
    }//GEN-LAST:event_jButtonFamiliaActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        // TODO add your handling code here:
        TelaProduto TelaProduto = new TelaProduto(usuario);
        TelaProduto.setVisible(true);
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBanco;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonComprador;
    private javax.swing.JButton jButtonCondicao;
    private javax.swing.JButton jButtonFamilia;
    private javax.swing.JButton jButtonFornecedor;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonStatus;
    private javax.swing.JButton jButtonUtilizacao;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
